### ISSUE TITLE
Fetch Call for word Data

### ISSUE THREAD

**Issue by favro03** [cjsopoco/Word-Facts#7]
- Create a form for the user to enter words 
- Search for Words Api data based on the input from the user form
- Display the definition, rhymes, synonyms, syllables, frequency of usage, and pronunciation of the word to the screen

**Comment by randomguy1234** [comment]
Due to limitations on accessing Words Api we decided to switch to Free Dictionary Api. 

As a result of this, the option to display rhymes, syllables, and frequency of usage of/for a word was committed out from the html file.
