### ISSUE TITLE
Famous Quotes Fetch

### ISSUE THREAD

**Issue by favro03** [cjsopoco/Word-Facts#8]
- Create a fetch call to Random Famous Quotes 
- Display a quote on the screen based on the word searched
- Set a maximum quote limit on the screen to 5 quotes

**Comment by randomguy1234** [comment]
Due to limitations in accessing the Random Famous Quotes Api, we replaced it with the Quotes Api. 

We were also unable to implement the 5 quote limit due to time constraints.
